kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswallsource-pv
  labels:
    type: local
    usage: glasswallsource-pv
spec:
  #storageClassName: azurefile
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/rebuild-data-in"