apiVersion: v1
kind: Service
metadata:
  name: icap-svc-host
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  externalIPs:
  - 127.0.0.1
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 1344
    protocol: TCP
    targetPort: 1344
  - name: port-2
    port: 1345
    protocol: TCP
    targetPort: 1345
  selector:
    app: adaptation
  type: LoadBalancer
