apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
  ports:
  - name: amqp
    port: {{ .Values.rabbitmqService.port }}
  - name: stats
    port: {{ .Values.rabbitmqService.managementPort }}
  selector:
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}
