apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqController.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmqController.app }}
        component: {{ .Values.rabbitmqService.component }}
    spec:
      containers:
      - image: {{ .Values.rabbitmqController.image }}
        name: {{ regexReplaceAll "\\W+" .Values.rabbitmqController.image "-" }}
        ports:
        - containerPort: {{ .Values.rabbitmqController.port }}
        resources:
          limits:
            cpu: {{ .Values.rabbitmqController.cpu }}